import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:intl/intl.dart';

import '../../../data/models/health_models.dart';
import '../../controllers/dashboard_controller.dart';
import '../../widgets/empty_state.dart';
import '../../widgets/glass_panel.dart';

class AlertsScreen extends ConsumerWidget {
  const AlertsScreen({super.key});

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final state = ref.watch(dashboardControllerProvider);

    return state.when(
      data: (summary) {
        final alerts = summary?.alerts ?? summary?.activeAlerts ?? [];

        if (alerts.isEmpty) {
          return RefreshIndicator(
            onRefresh: () async {
              HapticFeedback.lightImpact();
              await ref.read(dashboardControllerProvider.notifier).refresh();
            },
            child: ListView(
              physics: const AlwaysScrollableScrollPhysics(),
              padding: const EdgeInsets.all(20),
              children: [
                EmptyState(
                  icon: Icons.shield_rounded,
                  title: 'No alerts yet',
                  message:
                      'Health alerts generated by your thresholds will appear here with active and resolved history.',
                  action: OutlinedButton.icon(
                    onPressed: () {
                      HapticFeedback.lightImpact();
                      ref.read(dashboardControllerProvider.notifier).refresh();
                    },
                    icon: const Icon(Icons.refresh_rounded),
                    label: const Text('Check now'),
                  ),
                ),
              ],
            ),
          );
        }

        return RefreshIndicator(
          onRefresh: () async {
            HapticFeedback.lightImpact();
            await ref.read(dashboardControllerProvider.notifier).refresh();
          },
          child: ListView.separated(
            physics: const AlwaysScrollableScrollPhysics(),
            padding: const EdgeInsets.fromLTRB(20, 18, 20, 28),
            itemBuilder: (context, index) => _AlertTile(alert: alerts[index]),
            separatorBuilder: (context, index) => const SizedBox(height: 12),
            itemCount: alerts.length,
          ),
        );
      },
      loading: () => const Center(child: CircularProgressIndicator()),
      error: (error, stackTrace) => RefreshIndicator(
        onRefresh: () async {
          HapticFeedback.lightImpact();
          await ref.read(dashboardControllerProvider.notifier).refresh();
        },
        child: ListView(
          physics: const AlwaysScrollableScrollPhysics(),
          padding: const EdgeInsets.all(20),
          children: [
            EmptyState(
              icon: Icons.error_outline_rounded,
              title: 'Unable to load alerts',
              message: error.toString(),
            ),
          ],
        ),
      ),
    );
  }
}

class _AlertTile extends ConsumerWidget {
  const _AlertTile({required this.alert});

  final HealthAlertModel alert;

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final theme = Theme.of(context);
    final color = switch (alert.severity) {
      'critical' => const Color(0xFFEF4444),
      'warning' => const Color(0xFFF59E0B),
      _ => theme.colorScheme.primary,
    };

    return GlassPanel(
      padding: const EdgeInsets.all(18),
      borderRadius: 22,
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Row(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              Container(
                width: 44,
                height: 44,
                decoration: BoxDecoration(
                  color: color.withValues(alpha: 0.12),
                  borderRadius: BorderRadius.circular(16),
                ),
                child: Icon(Icons.notification_important_rounded, color: color),
              ),
              const SizedBox(width: 12),
              Expanded(
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    Text(
                      alert.title,
                      style: theme.textTheme.titleMedium?.copyWith(
                        fontWeight: FontWeight.w900,
                      ),
                    ),
                    const SizedBox(height: 4),
                    Text(
                      DateFormat('MMM d, h:mm a').format(alert.createdAt),
                      style: theme.textTheme.labelMedium?.copyWith(
                        color: theme.colorScheme.onSurfaceVariant,
                      ),
                    ),
                  ],
                ),
              ),
            ],
          ),
          const SizedBox(height: 14),
          Text(
            alert.message,
            style: theme.textTheme.bodyMedium?.copyWith(height: 1.45),
          ),
          const SizedBox(height: 14),
              Align(
                alignment: Alignment.centerRight,
                child: FilledButton.tonalIcon(
                  onPressed: () {
                    HapticFeedback.lightImpact();
                    ref
                        .read(dashboardControllerProvider.notifier)
                        .resolveAlert(alert.id);
                  },
                  icon: const Icon(Icons.check_circle_outline_rounded),
                  label: const Text('Resolve'),
                ),
          ),
        ],
      ),
    );
  }
}
